name = "rakshad1api"
main = "src/index.js"
compatibility_date = "2024-11-27"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "raksha"
database_id = "d4c93453-f9f9-4011-95bd-8e44b036d93a"
